<?php

use App\User;
Route::middleware('auth:api')->get('/user', function (Request $request) {
   return $request->user();
});

Route::group([

    'middleware' => 'api',
    'prefix' => 'auth'

], function ($router) {

    Route::post('login', 'AuthController@login');
    Route::post('logout', 'AuthController@logout');
    Route::post('refresh', 'AuthController@refresh');
    Route::post('me', 'AuthController@me');
    Route::post('/markNotification','AuthController@markNotification');
    Route::get('/getNotifications','AuthController@getNotifications');

    //-------------------------------------------------------------------------
    
Route::get('/getUserPermission/{name}','LoginController@getUserPermission');
Route::get('/getBIWSPermissions/{id}','LoginController@getBIWSPermissions');
Route::get('/getBIMSPrivillageDetails/{id}','LoginController@getBIMSPrivillageDetails');
Route::get('/passcheck/{username}{password}','LoginController@passcheck');
Route::get('/getHash','LoginController@getHash');
Route::get('/getMenuPermission/{id}','LoginController@getMenuPermission');
Route::post('/signupAssoc','LoginController@signupAssoc');
Route::post('/saveContractorDetails','LoginController@saveContractorDetails');
Route::post('/saveDetails','LoginController@saveDetails');
Route::post('/sendOTP','LoginController@sendOTP');
Route::post('/CreateToken','LoginController@CreateToken');
Route::post('/resetPassword','LoginController@resetPassword');
Route::post('/changeActiveStatus','LoginController@changeActiveStatus');
Route::get('/generateOTP','LoginController@generateOTP');
Route::get('/getAssocTypes','LoginController@getAssocTypes');
Route::get('/getUserTypes/{id}','LoginController@getUserTypes');

//-------------------------------------------------------
Route::post('/addLineItem','dashboardController@addLineItem');
Route::post('/saveKeys','dashboardController@saveKeys');
Route::post('/finishWO','dashboardController@finishWO');
Route::post('/saveCustKeys','dashboardController@saveCustKeys');
Route::post('/saveCustTerms','dashboardController@saveCustTerms');
Route::post('/actualAssocVisit','dashboardController@actualAssocVisit');
Route::post('/saveExtraServices','dashboardController@saveExtraServices');
Route::post('/savePriority','dashboardController@savePriority');
Route::post('/editPriority','dashboardController@editPriority');
Route::get('/getsession','dashboardController@getSession');
Route::get('/getQAVerify','dashboardController@getQAVerify');
Route::get('/getQACount','dashboardController@getQACount');
Route::get('/getEstCount/{name}','dashboardController@getEstCount');
Route::get('/getWOCount/{name}','dashboardController@getWOCount');
Route::get('/getAllServices','dashboardController@getAllServices');
Route::get('/getCountItems/{id}','dashboardController@getCountItems');
Route::get('/getFlagCount/{id}','dashboardController@getFlagCount');
Route::get('/getKeys/{id} ','dashboardController@getKeys');
Route::get('/getWOKeys/{id}','dashboardController@getWOKeys');
Route::get('/getQAPendList','dashboardController@getQAPendList');
Route::get('/getSiteVisitEnq/{name}','dashboardController@getSiteVisitEnq');
Route::get('/getSiteVisitPend/{name}','dashboardController@getSiteVisitPend');
Route::get('/getSiteVisitCount/{name}','dashboardController@getSiteVisitCount');
Route::get('/getSiteVisitPendCount/{name}','dashboardController@getSiteVisitPendCount');
Route::get('/getEstEnq/{name}','dashboardController@getEstEnq');
Route::get('/getWOEnq/{name}','dashboardController@getWOEnq');
Route::get('/getSiteVisitPendEnq/{name}','dashboardController@getSiteVisitPendEnq');
Route::get('/getRegisteredAssocList','dashboardController@getRegisteredAssocList');
Route::get('/getVerifiedAssocList','dashboardController@getVerifiedAssocList');
Route::get('/getCertifiedAssocList','dashboardController@getCertifiedAssocList');
Route::get('/getLostEnqDetails/{name}','dashboardController@getLostEnqDetails');
Route::get('/getLostEnqCount/{name}','dashboardController@getLostEnqCount');
Route::get('/getHotEnqDetails','dashboardController@getHotEnqDetails');
Route::get('/getWOComplEnqs/{name}','dashboardController@getWOComplEnqs');
Route::get('/getEstComplEnqs/{name}','dashboardController@getEstComplEnqs');
Route::get('/getEngineerCount','dashboardController@getEngineerCount');
Route::get('/getArchCount','dashboardController@getArchCount');
Route::get('/getVastuCount','dashboardController@getVastuCount');
Route::get('/getIntCount','dashboardController@getIntCount');
Route::get('/getContractCount','dashboardController@getContractCount');
Route::get('/getSuppliersCount','dashboardController@getSuppliersCount');
Route::get('/getArticleCount','dashboardController@getArticleCount');
Route::get('/getOnGoingProjects/{name}','dashboardController@getOnGoingProjects');
Route::get('/getStartProjectCount/{name}','dashboardController@getStartProjectCount');
Route::get('/getServiceNames/{id}','dashboardController@getServiceNames');
Route::get('/getWorkServices/{id}','dashboardController@getWorkServices');
//Route::get('/getEngDetails/{id}','dashboardController@getEngDetails');
Route::get('/getAmendLineItems/{id}/{no}','dashboardController@getAmendLineItems');
Route::get('/getAmendedLineItems/{id}/{no}','dashboardController@getAmendedLineItems');
Route::get('/getAmended1LineItems/{id}','dashboardController@getAmended1LineItems');
Route::get('/getAmended2LineItems/{id}','dashboardController@getAmended2LineItems');
Route::get('/getAmended3LineItems/{id}','dashboardController@getAmended3LineItems');
Route::get('/chkKeyDeliExists/{id}','dashboardController@chkKeyDeliExists');





Route::get('/getAssociate/{type}','certificationController@getAssociate');
Route::get('/getOneAssociate/{id}/{type}','certificationController@getOneAssociate');
Route::get('/getProject/{id}','certificationController@getProject');
Route::get('/getOneProjectFeed/{id}','certificationController@getOneProjectFeed');
Route::get('/getSegments','certificationController@getSegments');
Route::get('/getBranches','certificationController@getBranches');
Route::get('/getCategories/{id}','certificationController@getCategories');
Route::get('/getOneCategory/{id}','certificationController@getOneCategory');
Route::get('/getUnits','certificationController@getUnits');
Route::get('/getLocations','certificationController@getLocations');
Route::get('/getAssocSegments/{id}','certificationController@getAssocSegments');
Route::get('/getAssocServices/{aid}/{sid}','certificationController@getAssocServices');
Route::get('/getSegProjectDetails/{aid}/{sid}','certificationController@getSegProjectDetails');
Route::post('/addAssociate','certificationController@addAssociate');
Route::post('/addProject','certificationController@addProject');
Route::post('/addFeedback','certificationController@addFeedback');
Route::post('/addQARating','certificationController@addQARating');
Route::post('/editMaterialAssoc','certificationController@editMaterialAssoc');
Route::post('/addServiceDetails','certificationController@addServiceDetails');
Route::post('/updateRates','certificationController@updateRates');
Route::get('/getFeedback/{aid}','certificationController@getFeedback');
Route::get('/getFeedback','certificationController@getFeedback');
Route::get('/getOneProject/{id}','certificationController@getOneProject');
Route::get('/getOneCustomer1/{id}','certificationController@getOneCustomer1');
Route::get('/getOneCustomerqa/{id}','certificationController@getOneCustomerqa');
Route::get('/checkQACount/{id}','certificationController@checkQACount');
Route::post('/changeQAStatus','certificationController@changeQAStatus');
Route::get('/changeFeedStatus/{id}','certificationController@changeFeedStatus');
Route::get('/chkProjectExists/{id}','certificationController@chkProjectExists');
Route::post('/file_uploadAadhar','certificationController@file_uploadAadhar');
Route::post('/file_uploadAgreement','certificationController@file_uploadAgreement');
Route::post('/certification','certificationController@certification');
Route::get('/getSegRate/{id}','certificationController@getSegRate');
Route::get('/getQAProject/{id}','certificationController@getQAProject');
Route::post('/saveRate','certificationController@saveRate');
Route::get('/getServiceList/{id}','certificationController@getServiceList');
Route::get('/changeRegStatus/{id}','certificationController@changeRegStatus');
Route::get('/changeVerifyStatus/{id}','certificationController@changeVerifyStatus');
Route::get('/changeCertifyStatus/{id}','certificationController@changeCertifyStatus');
Route::any('/getUserName/{id}','certificationController@getUserName');
Route::post('/createLogin','certificationController@createLogin');
Route::get('/getHash/{value}','certificationController@getHash');
Route::post('/addAvgRating','certificationController@addAvgRating');
Route::get('/getSegmentDetails/{id}','certificationController@getSegmentDetails');
Route::get('/searchAssociate/{value}','certificationController@searchAssociate');
Route::get('/getCategory/{id}','certificationController@getCategory');
Route::get('/getSegmentAssoc/{id}','certificationController@getSegmentAssoc');
Route::get('/getUserPermission/{name}','certificationController@getUserPermission');
Route::post('/addUpdateLog','certificationController@addUpdateLog');
Route::post('/addRegisterLog','certificationController@addRegisterLog');
Route::post('/addCertifyLog','certificationController@addCertifyLog');
Route::post('/addMaterialAssoc','certificationController@addMaterialAssoc');
Route::get('/getAssociateRole/{name}','certificationController@getAssociateRole');
Route::get('/getProdAssocSegments/{id}','certificationController@getProdAssocSegments');
Route::get('/getAssocRates/{id}','certificationController@getAssocRates');
Route::get('/downloadAadhar/{id}','certificationController@downloadAadhar');
Route::get('/downloadAgreement/{id}','certificationController@downloadAgreement');
Route::post('/updateAssociate','certificationController@updateAssociate');
Route::get('/getAssocSource','certificationController@getAssocSource');
Route::get('/getCertfAssocs','certificationController@getCertfAssocs');
Route::get('/getPendingCert','certificationController@getPendingCert');
Route::get('/getTotalReg','certificationController@getTotalReg');
Route::get('/chkAssocDocExists/{id}','certificationController@chkAssocDocExists');
Route::get('/getMatAssocSegments/{id}','certificationController@getMatAssocSegments');
Route::get('/getAssocDocs/{id}','certificationController@getAssocDocs');
Route::get('/docDownload/{type}/{id}','certificationController@docDownload');
Route::get('/getMaterialAssociates','certificationController@getMaterialAssociates');
Route::get('/getServiceAssociate','certificationController@getServiceAssociate');
Route::get('/getProductSegments','certificationController@getProductSegments');
Route::post('/getProductGroup','certificationController@getProductGroup');
Route::post('/removeSegmentGroup','certificationController@removeSegmentGroup');
Route::post('/addNewSegment','certificationController@addNewSegment');

//MatAssocCertController
Route::get('/getMatAssociates','matAssocCertController@getMatAssociates');


//PriceManagementController
Route::get('/getServices','priceManagementController@getServices');
Route::get('/getProducts','priceManagementController@getProducts');
Route::get('/getAssocRateList/{id}','priceManagementController@getAssocRateList');
Route::get('/getServAssocRate/{value}','priceManagementController@getServAssocRate');
Route::get('/getProdAssociates/{id}','priceManagementController@getProdAssociates');
Route::get('/getServAssociates/{id}','priceManagementController@getServAssociates');
Route::get('/getNewProdLists','priceManagementController@getNewProdLists');
Route::post('/addProductRate','priceManagementController@addProductRate');
Route::post('/addServiceRate','priceManagementController@addServiceRate');
Route::get('/changeStatus/{id}','priceManagementController@changeStatus');
Route::get('/products','priceManagementController@products');
Route::get('/getDetails','priceManagementController@getDetails');

//AdminController
/*Route::get('/getBrands','adminController@getBrands');
Route::get('/getTotalWorks','adminController@getTotalWorks');
Route::get('/getSerLineItems/{id}','adminController@getSerLineItems');
Route::get('/getServKeys/{id}','adminController@getServKeys');
Route::get('/getGroups','adminController@getGroups');
Route::get('/getCategories','adminController@getCategories');
Route::get('/getGroupSegments/{id}','adminController@getGroupSegments');
Route::post('/addNewBrand','adminController@addNewBrand');
Route::post('/addNewCat','adminController@addNewCat');
Route::post('/addNewSubCat','adminController@addNewSubCat');
Route::post('/addNewSeg','adminController@addNewSeg');
Route::get('/getAdminSegments','adminController@getAdminSegments');
Route::get('/getSerSegments','adminController@getSerSegments');
Route::get('/getAttributes','adminController@getAttributes');
Route::get('/getCatGroups/{id}','adminController@getCatGroups');
Route::get('/getSubCatByCat/{id}','adminController@getSubCatByCat');
Route::get('/setVerified/{id}','adminController@setVerified');
Route::post('/addNewGroup','adminController@addNewGroup');
Route::post('/addCSVFile','adminController@addCSVFile');
Route::post('/saveFeedback','adminController@saveFeedback');
Route::post('/addLineItemsCSV','adminController@addLineItemsCSV');
Route::post('/addNewSerSeg','adminController@addNewSerSeg');addSegment

Route::post('/addNewSerCat','adminController@addNewSerCat');
Route::post('/addNewProduct','adminController@addNewProduct');
Route::post('/addNewAttrb','adminController@addNewAttrb');
Route::post('/addNewItem','adminController@addNewItem');
Route::post('/saveQAFeedback','adminController@saveQAFeedback');
Route::post('/postQAFiles','adminController@postQAFiles');
Route::post('/rejectArticle','adminController@rejectArticle');
Route::get('/getServices/{id}','adminController@getServices');
Route::get('/getAssocTypeList/{id}','adminController@getAssocTypeList');
Route::get('/getAssocServiceList/{id}','adminController@getAssocServiceList');
Route::get('/getServCustomers/{id}/{aid}','adminController@getServCustomers');
Route::get('/getFeedCustomers/{id}/{aid}','adminController@getFeedCustomers');
Route::get('/getCustomerDetails/{id}/{sid}','adminController@getCustomerDetails');
Route::get('/checkFeedCount/{id}','adminController@checkFeedCount');
Route::get('/changeVerifyStatus/{id}','adminController@changeVerifyStatus');
Route::get('/checkTotalFeedCount/{id}','adminController@checkTotalFeedCount');
//Route::get('/checkQACount/{id}','adminController@checkQACount');
Route::get('/getAssocCustList/{id}','adminController@getAssocCustList');
Route::get('/getAssocCustListQA/{id}','adminController@getAssocCustListQA');
Route::get('/getServiceList/{cid}/{aid}','adminController@getServiceList');
Route::get('/getServiceListQA/{cid}/{aid}','adminController@getServiceListQA');
Route::get('/getAssocServiceDetails/{cid}/{aid}','adminController@getAssocServiceDetails');
Route::get('/getAssocServiceDetailsQA/{sid}/{aid}/{cid}','adminController@getAssocServiceDetailsQA');
Route::get('/changeQAStatus/{sid}','adminController@changeQAStatus');
Route::get('/getUserID/{id}','adminController@getUserID');
Route::get('/getProfileDetailsAdmin/{id}','adminController@getProfileDetailsAdmin');
Route::get('/getAssocTypeAdmin/{id}','adminController@getAssocTypeAdmin');
Route::get('/getArticlesList','adminController@getArticlesList');
Route::get('/verifyArticle/{id}','adminController@verifyArticle');
Route::get('/getAllArticles','adminController@getAllArticles');
Route::get('/getArticleByAssoc/{id}','adminController@getArticleByAssoc');*/
Route::post('/addSegment','adminController@addSegment');
Route::post('/addService','adminController@addService');
Route::post('/addItem','adminController@addItem');
Route::post('/getFilteredAssocs','adminController@getFilteredAssocs');
Route::post('/addNewService','adminController@addNewService');
Route::post('/addNewProdSeg','adminController@addNewProdSeg');
Route::post('/addProdGroup','adminController@addProdGroup');
Route::get('/getItemsByServ/{id}','adminController@getItemsByServ');
Route::get('/getAssoServices/{id}','adminController@getAssoServices');
Route::get('/deleteRate/{id}','adminController@deleteRate');
Route::get('/getProdGroups','adminController@getProdGroups');




//SalesModule Controller
Route::get('/getSalesStatus','salesModuleController@getSalesStatus');
Route::get('/getTotalEnqNo/{name}','salesModuleController@getTotalEnqNo');
Route::get('/getTotalPendingNo','salesModuleController@getTotalPendingNo');
Route::get('/getTotalEnqDetails/{name}','salesModuleController@getTotalEnqDetails');
Route::get('/getTotalHotEnq/{name}','salesModuleController@getTotalHotEnq');
Route::get('/getCustomerAppEnqNo/{name}','salesModuleController@getCustomerAppEnqNo');
Route::get('/getCustomerAppEnqDetails/{name}','salesModuleController@getCustomerAppEnqDetails');

Route::get('/getLeadFollowups','salesModuleController@getLeadFollowups');
Route::get('/getAllMigrateData','salesModuleController@getAllMigrateData');
Route::get('/getReqAnalysisRemind','salesModuleController@getReqAnalysisRemind');
Route::get('/getPendingAnalysis','salesModuleController@getPendingAnalysis');
Route::get('/getLeadPendings','salesModuleController@getLeadPendings');
Route::get('/getReqQuoteRemind','salesModuleController@getReqQuoteRemind');
Route::get('/getPendingQuote','salesModuleController@getPendingQuote');
Route::get('/getAllCustomers','salesModuleController@getAllCustomers');
Route::get('/getOneCustomer/{id}','salesModuleController@getOneCustomer');
Route::post('/getSegCategories','salesModuleController@getSegCategories');
Route::get('/getServiceIDs/{id}','salesModuleController@getServiceIDs');
Route::get('/getCategories','salesModuleController@getCategories');
Route::get('/getSources','salesModuleController@getSources');
Route::get('/getAllLeads/{name}','salesModuleController@getAllLeads');
Route::get('/getFullLeads','salesModuleController@getFullLeads');
Route::get('/getActivity','salesModuleController@getActivity');
Route::get('/getAllWork/{id}','salesModuleController@getAllWork');
Route::get('/getAllTempWork/{id}','salesModuleController@getAllTempWork');
Route::get('/getOneLead/{id}','salesModuleController@getOneLead');
Route::get('/getWorkStatus','salesModuleController@getWorkStatus');
Route::get('/getPMQALeadList','salesModuleController@getPMQALeadList');
Route::get('/getPMQAWorks','salesModuleController@getPMQAWorks');
Route::get('/getOneWork/{id}','salesModuleController@getOneWork');
Route::get('/getOneWork1/{id}','salesModuleController@getOneWork1');
Route::get('/getServiceList/{id}','salesModuleController@getServiceList');
Route::get('/getOnePMQAWorks/{id}','salesModuleController@getOnePMQAWorks');
Route::get('/checkWorkUpdate/{id}','salesModuleController@checkWorkUpdate');
Route::get('/getAssignee/{id}','salesModuleController@getAssignee');
Route::get('/checkWorkType/{id}','salesModuleController@checkWorkType');
Route::get('/checkDesign/{id}','salesModuleController@checkDesign');
Route::get('/getProductsList/{id}','salesModuleController@getProductsList');
Route::get('/getAllLineItems/{id}','salesModuleController@getAllLineItems');
Route::get('/chkLineItemsExists/{id}','salesModuleController@chkLineItemsExists');
Route::get('/getUnitofProduct/{id}','salesModuleController@getUnitofProduct');
Route::get('/getLeadDetails/{id}','salesModuleController@getLeadDetails');
Route::get('/getLeadHistory/{id}','salesModuleController@getLeadHistory');
Route::get('/getTotalMatEst/{id}','salesModuleController@getTotalMatEst');
Route::get('/getAllLabEst/{id}','salesModuleController@getAllLabEst');
Route::get('/getallMatEstimate/{id}','salesModuleController@getallMatEstimate');
Route::get('/downloadDesign/{id}','salesModuleController@downloadDesign');
Route::get('/getTotalMatEst/{id}','salesModuleController@getTotalMatEst');
Route::get('/getWorkItems/{id}','salesModuleController@getWorkItems');
Route::get('/getWorkItemsCount/{id}','salesModuleController@getWorkItemsCount');
Route::get('/getAllWorkList/{name}','salesModuleController@getAllWorkList');
Route::get('/getAllSalesWorkList','salesModuleController@getAllSalesWorkList');
Route::get('/getTotalLabEst/{id}','salesModuleController@getTotalLabEst');
Route::get('/getItemName/{id}','salesModuleController@getItemName');
Route::get('/getAllWorkLineItems/{id}','salesModuleController@getAllWorkLineItems');
Route::get('/getUsersList','salesModuleController@getUsersList');
Route::post('/addCustomer','salesModuleController@addCustomer');
Route::post('/changeLeadStatus','salesModuleController@changeLeadStatus');
Route::post('/saveLabDetails','salesModuleController@saveLabDetails');
Route::post('/saveMatLabDetails','salesModuleController@saveMatLabDetails');
Route::post('/addLead','salesModuleController@addLead');
Route::post('/saveWork','salesModuleController@saveWork');
Route::post('/updateLead','salesModuleController@updateLead');
Route::post('/updateWork','salesModuleController@updateWork');
Route::post('/design_upload','salesModuleController@design_upload');
Route::get('/designExists/{id}','salesModuleController@designExists');
Route::post('/addMatEstimation','salesModuleController@addMatEstimation');
Route::post('/updatePMQAWork','salesModuleController@updatePMQAWork');
Route::post('/addLabEstimation','salesModuleController@addLabEstimation');
Route::post('/addProductList','salesModuleController@addProductList');
Route::post('/saveCustLabItems','salesModuleController@saveCustLabItems');
Route::post('/saveCustLabMatItems','salesModuleController@saveCustLabMatItems');
Route::post('/saveProdDetails','salesModuleController@saveProdDetails');
Route::post('/updateWorkStatus','salesModuleController@updateWorkStatus');
Route::post('/updateAssocVisit','salesModuleController@updateAssocVisit');
Route::post('/addLabLineItem','salesModuleController@addLabLineItem');
Route::get('/removeMatItem/{id}','salesModuleController@removeMatItem');
Route::get('/getLineItemName/{id}','salesModuleController@getLineItemName');
Route::get('/getAssocVisitDate/{id}','salesModuleController@getAssocVisitDate');
Route::get('/removeLabItem/{id}','salesModuleController@removeLabItem');
Route::get('/getDeptAssignee/{id}','salesModuleController@getDeptAssignee');
Route::get('/getAllMatLabEst/{id}','salesModuleController@getAllMatLabEst');
Route::get('/getDepts','salesModuleController@getDepts');
Route::get('/getTotalMatLabEst/{id}','salesModuleController@getTotalMatLabEst');
Route::get('/getLabMatLineItemName/{id}','salesModuleController@getLabMatLineItemName');
Route::get('/removeLabMatItem/{id}','salesModuleController@removeLabMatItem');
Route::get('/finishEstimate/{id}','salesModuleController@finishEstimate');
Route::get('/changeStatusEst/{id}','salesModuleController@changeStatusEst');
Route::get('/findLeadID/{id}','salesModuleController@findLeadID');
Route::get('/getFullWorkList','salesModuleController@getFullWorkList');
Route::get('/getAccessData/{id}','salesModuleController@getAccessData');
Route::get('/getData/{id}','salesModuleController@getData');
Route::post('/addMatLabLineItem','salesModuleController@addMatLabLineItem');
Route::post('/saveWorkSales','salesModuleController@saveWorkSales');

//tendering controller
Route::get('/getAllBIWorkList/{name}','tenderingController@getAllBIWorkList');
Route::get('/getPaySubTotal/{id}','tenderingController@getPaySubTotal');
Route::get('/getPendingTotal/{id}','tenderingController@getPendingTotal');
Route::get('/getTotalWOEnq/{name}','tenderingController@getTotalWOEnq');
Route::get('/getTotalTenderPend/{name}','tenderingController@getTotalTenderPend');
Route::get('/getTotalTenderReq/{name}','tenderingController@getTotalTenderReq');
Route::get('/getTotalWO/{name}','tenderingController@getTotalWO');
Route::get('/getPaymentReminderCount/{name}','tenderingController@getPaymentReminderCount');
Route::get('/getPaymentReminderEnq/{name}','tenderingController@getPaymentReminderEnq');
Route::get('/getMatLabLineItemID/{id}','tenderingController@getMatLabLineItemID');
Route::get('/getAssignees/{name}','tenderingController@getAssignees');
Route::get('/getCertifyAssocList/{id}','tenderingController@getCertifyAssocList');
Route::get('/getAssocList','tenderingController@getAssocList');
Route::get('/getSelectedAssocs/{id}','tenderingController@getSelectedAssocs');
Route::get('/getSelectedAssocsUpdated/{id}','tenderingController@getSelectedAssocsUpdated');
Route::get('/changeUpdateFlag/{id}','tenderingController@changeUpdateFlag');
Route::get('/getTenderAssocs/{id}','tenderingController@getTenderAssocs');
Route::get('/chkDisableQuote/{id}','tenderingController@chkDisableQuote');
Route::get('/getAssocName/{id}','tenderingController@getAssocName');
Route::get('/getWorkType/{id}','tenderingController@getWorkType');
Route::get('/getallMatEstimateTender/{id}','tenderingController@getallMatEstimateTender');
Route::get('/finalizeAssoc/{id}','tenderingController@finalizeAssoc');
Route::get('/getAssocDetails/{id}','tenderingController@getAssocDetails');
Route::get('/getAssocDetailsWO/{id}','tenderingController@getAssocDetailsWO');
Route::get('/getTenderDetails/{tid}','tenderingController@getTenderDetails');
Route::get('/getWorkTenderDetails/{id}','tenderingController@getWorkTenderDetails');
Route::get('/finishTender/{id}','tenderingController@finishTender');
Route::get('/checkAssocSelected/{id}','tenderingController@checkAssocSelected');
Route::get('/getTenderedAssocs/{id}','tenderingController@getTenderedAssocs');
Route::get('/reTender/{id}','tenderingController@reTender');
Route::get('/reEstimate/{id}','tenderingController@reEstimate');
Route::get('/removeAssocName/{id}','tenderingController@removeAssocName');
Route::get('/getCountItemsLab/{id}','tenderingController@getCountItemsLab');
Route::get('/getCountItemsLabTender/{id}','tenderingController@getCountItemsLabTender');
Route::get('/getCountFlagsLabTender/{id}','tenderingController@getCountFlagsLabTender');
Route::get('/getCountFlagsLab/{id}','tenderingController@getCountFlagsLab');
Route::get('/getTotalQuote/{id}','tenderingController@getTotalQuote');
Route::get('/getAssocTender/{id}','tenderingController@getAssocTender');
Route::get('/getAssocFlag/{id}','tenderingController@getAssocFlag');
Route::get('/getAssocTenderDetails/{id}','tenderingController@getAssocTenderDetails');
Route::get('/getWorkID/{id}','tenderingController@getWorkID');
Route::get('/getPaymentTerms/{value}','tenderingController@getPaymentTerms');
Route::get('/getWorkSchedule/{id}','tenderingController@getWorkSchedule');
Route::get('/chkPaySchedExists/{id}','tenderingController@chkPaySchedExists');
Route::get('/chkWorkSchedExists/{id}','tenderingController@chkWorkSchedExists');
Route::get('/getPaySchedule/{id}','tenderingController@getPaySchedule');
Route::get('/getTermsConditions/{id}','tenderingController@getTermsConditions');
Route::get('/getTerms/{id}','tenderingController@getTerms');
Route::get('/getLineItemID/{id}','tenderingController@getLineItemID');
Route::get('/chkAssocDelFlag/{id}','tenderingController@chkAssocDelFlag');
Route::get('/getSelectedTenderAssocs/{id}','tenderingController@getSelectedTenderAssocs');
Route::get('/getFinalLabTenderDetails/{id}','tenderingController@getFinalLabTenderDetails');
Route::get('/getCustomerDetails/{id}','tenderingController@getCustomerDetails');
Route::get('/getCustomer/{id}','tenderingController@getCustomer');
Route::get('/getDetails/{id}','tenderingController@getDetails');
Route::get('/getMatSpec/{id}','tenderingController@getMatSpec');
Route::get('/getIssueDate/{id}','tenderingController@getIssueDate');
Route::get('/testFunc','tenderingController@testFunc');
Route::get('/getFinalTender/{id}','tenderingController@getFinalTender');
Route::get('/getFinalTenderAssoc/{id}','tenderingController@getFinalTenderAssoc');
Route::get('/checkPaymentTermsExists/{id}','tenderingController@checkPaymentTermsExists');
Route::get('/chkKeysExists/{id}','tenderingController@chkKeysExists');
Route::get('/checkTermsExists/{id}','tenderingController@checkTermsExists');
Route::get('/getOneWorkSchedDetails/{id}','tenderingController@getOneWorkSchedDetails');
Route::get('/getOnePaySchedDetails/{id}','tenderingController@getOnePaySchedDetails');
Route::get('/chkAmendKeysExists/{id}/{no}','tenderingController@chkAmendKeysExists');
Route::get('/checkAmendTermsExists/{id}/{no}','tenderingController@checkAmendTermsExists');
Route::get('/chkAmendWorkSchedExists/{id}/{no}','tenderingController@chkAmendWorkSchedExists');
Route::get('/chkAmendPaySchedExists/{id}/{no}','tenderingController@chkAmendPaySchedExists');
Route::get('/chkAmendLineItemsExists/{id}/{no}','tenderingController@chkAmendLineItemsExists');
Route::get('/getTenderTerms/{id}','tenderingController@getTenderTerms');
Route::get('/chkServiceAssocExists/{id}','tenderingController@chkServiceAssocExists');
Route::get('/getLineItemRate/{id}','tenderingController@getLineItemRate');
Route::get('/getTenderTotals/{id}','tenderingController@getTenderTotals');
Route::get('/getLineItemByService/{id}','tenderingController@getLineItemByService');
Route::get('/getAssocByService/{id}','tenderingController@getAssocByService');
Route::get('/getTermsConditionWO/{id}','tenderingController@getTermsConditionWO');
Route::get('/chkTemplateWorkID/{id}','tenderingController@chkTemplateWorkID');
Route::post('/getEndDate','tenderingController@getEndDate');
Route::post('/updateAssignees','tenderingController@updateAssignees');
Route::post('/saveAssocList','tenderingController@saveAssocList');
Route::post('/saveTenderMatDetails','tenderingController@saveTenderMatDetails');
Route::post('/saveTenderLabDetails','tenderingController@saveTenderLabDetails');
Route::post('/addPaymentTerms','tenderingController@addPaymentTerms');
Route::post('/saveWorkSchedule','tenderingController@saveWorkSchedule');
Route::post('/savePaymentSchedule','tenderingController@savePaymentSchedule');
Route::post('/saveTerms','tenderingController@saveTerms');
Route::post('/addTenderLabItems','tenderingController@addTenderLabItems');
Route::post('/addTenderMatLabItems','tenderingController@addTenderMatLabItems');
Route::post('/updateWOIssueDate','tenderingController@updateWOIssueDate');
Route::post('/signedWO','tenderingController@signedWO');
Route::post('/initiateWO','tenderingController@initiateWO');
Route::post('/editWorkSchDetails','tenderingController@editWorkSchDetails');
Route::post('/deleteWorkSch','tenderingController@deleteWorkSch');
Route::post('/deletePaySched','tenderingController@deletePaySched');
Route::post('/editPaySchDetails','tenderingController@editPaySchDetails');
Route::post('/woSignUp','tenderingController@woSignUp');
Route::post('/woSignedUp','tenderingController@woSignedUp');
Route::post('/reEstimateTender','tenderingController@reEstimateTender');
Route::post('/addTemplateEst','tenderingController@addTemplateEst');
Route::post('/addTempSchedules','tenderingController@addTempSchedules');


//profileController
Route::post('/profileUpload','profileController@profileUpload');
Route::post('/editProfileDetails','profileController@editProfileDetails');
Route::post('/postComment','profileController@postComment');
Route::get('/deletePost/{id}','profileController@deletePost');
Route::get('/getPostFiles/{id}','profileController@getPostFiles');
Route::get('/getProfileDetails/{id}','profileController@getProfileDetails');
Route::get('/getAssociateType/{id}','profileController@getAssociateType');
Route::get('/getArticleOnTimeline/{id}','profileController@getArticleOnTimeline');
Route::get('/getPhotosVideos/{id}','profileController@getPhotosVideos');
Route::get('/getActivityDetails/{id}','profileController@getActivityDetails');
Route::get('/viewArticle/{id}','profileController@viewArticle');
Route::get('/sharePost/{id}/{uid}','profileController@sharePost');
Route::get('/getSharedPosts/{id}','profileController@getSharedPosts');
Route::get('/getCivilServices','profileController@getCivilServices');
Route::get('/getSegments','profileController@getSegments');
Route::get('/getPostFiles/{id}','profileController@getPostFiles');
Route::get('/deleteArticle/{id}','profileController@deleteArticle');
Route::post('/saveServices','profileController@saveServices');
Route::post('/saveArticle','profileController@saveArticle');

//-------------ProjectManagement COntroller--------------------

Route::post('/workStart', 'projectManagement@workStart');
Route::post('/updateTransactionDetails', 'projectManagement@updateTransactionDetails');
Route::post('/saveWorkDate', 'projectManagement@saveWorkDate');
Route::post('/savePayDate', 'projectManagement@savePayDate');
Route::post('/savePRItemDetails', 'projectManagement@savePRItemDetails');
Route::post('/savePO', 'projectManagement@savePO');
Route::post('/addSupplier', 'projectManagement@addSupplier');
Route::post('/editPRItemDetails', 'projectManagement@editPRItemDetails');
Route::post('/updateContractorPaymentDetails', 'projectManagement@updateContractorPaymentDetails');
Route::post('/updateSupplierPaymentDetails', 'projectManagement@updateSupplierPaymentDetails');
Route::post('/updateGoodsDate', 'projectManagement@updateGoodsDate');
Route::post('/initiatePayment', 'projectManagement@initiatePayment');
Route::post('/updateMFee', 'projectManagement@updateMFee');
Route::post('/approveInitPay', 'projectManagement@approveInitPay');
Route::post('/updateContractorInitPaymentDetails', 'projectManagement@updateContractorInitPaymentDetails');
Route::post('/finishAmend', 'projectManagement@finishAmend');
Route::post('/saveReMeasureDetails', 'projectManagement@saveReMeasureDetails');
Route::post('/updateWOMFee', 'projectManagement@updateWOMFee');
//Route::post('/finishReMeasure', 'projectManagement@finishReMeasure');
Route::post('/finishWork', 'projectManagement@finishWork');
Route::post('/updateAmendIssueDate', 'projectManagement@updateAmendIssueDate');
Route::post('/saveExtraPayment', 'projectManagement@saveExtraPayment');
Route::post('/updateReceivedPayment', 'projectManagement@updateReceivedPayment');
Route::post('/updateRemeasureIssueDate', 'projectManagement@updateRemeasureIssueDate');
Route::post('/generateReport', 'projectManagement@generateReport');
Route::post('/workLost', 'projectManagement@workLost');
Route::post('/updateAmendReason', 'projectManagement@updateAmendReason');
Route::get('/getFilteredRecPay/{wid}/{cid}/{tid}', 'projectManagement@getFilteredRecPay');
Route::get('/getPRDetails/{id}', 'projectManagement@getPRDetails');
Route::get('/getPRCount/{id}', 'projectManagement@getPRCount');
Route::get('/getPRDetailsForPO', 'projectManagement@getPRDetailsForPO');
Route::get('/getSuppliers', 'projectManagement@getSuppliers');
Route::get('/getPRDetailsForGoods/{id}', 'projectManagement@getPRDetailsForGoods');
Route::get('/getItemDetails/{id}', 'projectManagement@getItemDetails');
Route::get('/deletePR/{id}', 'projectManagement@deletePR');
Route::get('/getBIPRDetails', 'projectManagement@getBIPRDetails');
Route::get('/getOnGoingProjectsBI', 'projectManagement@getOnGoingProjectsBI');
Route::get('/getOnePRDetailsForPO/{id}', 'projectManagement@getOnePRDetailsForPO');
Route::get('/getContractorPayDetails', 'projectManagement@getContractorPayDetails');
Route::get('/approvePayment/{id}', 'projectManagement@approvePayment');
Route::get('/getApprovedPayDetails', 'projectManagement@getApprovedPayDetails');
Route::get('/getOneContractorPayDetails/{id}', 'projectManagement@getOneContractorPayDetails');
Route::get('/getWorkPOList/{id}', 'projectManagement@getWorkPOList');
Route::get('/getPOItemList/{id}', 'projectManagement@getPOItemList');
Route::get('/getSupplierPayDetails', 'projectManagement@getSupplierPayDetails');
Route::get('/approveSuppPayment/{id}', 'projectManagement@approveSuppPayment');
Route::get('/getApprovedSuppPayDetails', 'projectManagement@getApprovedSuppPayDetails');
Route::get('/getInitiatePayDetails/{id}', 'projectManagement@getInitiatePayDetails');
Route::get('/getOneInitiatePay/{id}', 'projectManagement@getOneInitiatePay');
Route::get('/getAllInitiatePayDetails', 'projectManagement@getAllInitiatePayDetails');
Route::get('/getOneContractorInitPayDetails/{id}', 'projectManagement@getOneContractorInitPayDetails');
Route::get('/getAllSupplPayDetails', 'projectManagement@getAllSupplPayDetails');
Route::get('/getOneSupplierPayDetails/{id}', 'projectManagement@getOneSupplierPayDetails');
Route::get('/getTotalAmendItems/{id}/{no}', 'projectManagement@getTotalAmendItems');
Route::get('/getTotalAmend1Items/{id}/{no}', 'projectManagement@getTotalAmend1Items');
Route::get('/getTotalAmend2Items/{id}/{no}', 'projectManagement@getTotalAmend2Items');
Route::get('/getTotalAmend3Items/{id}/{no}', 'projectManagement@getTotalAmend3Items');
Route::get('/getReTotalAmend1Items/{id}/{no}', 'projectManagement@getReTotalAmend1Items');
Route::get('/getReTotalAmend2Items/{id}/{no}', 'projectManagement@getReTotalAmend2Items');
Route::get('/getReTotalAmend3Items/{id}/{no}', 'projectManagement@getReTotalAmend3Items');
Route::get('/getAmendWorkSchedule/{id}/{no}', 'projectManagement@getAmendWorkSchedule');
Route::get('/getAmendPaySchedule/{id}/{no}', 'projectManagement@getAmendPaySchedule');
Route::get('/getAmendKeyDeliverables/{id}/{no}', 'projectManagement@getAmendKeyDeliverables');
Route::get('/getAmendTerms/{id}/{no}', 'projectManagement@getAmendTerms');
Route::get('/getAmendedWorkSchedule/{id}/{no}', 'projectManagement@getAmendedWorkSchedule');
Route::get('/getAmendedPaySchedule/{id}/{no}', 'projectManagement@getAmendedPaySchedule');
Route::get('/getAmendedKeyDeliverables/{id}/{no}', 'projectManagement@getAmendedKeyDeliverables');
Route::get('/getAmendedTerms/{id}/{no}', 'projectManagement@getAmendedTerms');
Route::get('/getGrandTotal/{id}', 'projectManagement@getGrandTotal');
Route::get('/getTenderItemDetails/{id}', 'projectManagement@getTenderItemDetails');
Route::get('/getReMeasuredTenderDetails/{id}', 'projectManagement@getReMeasuredTenderDetails');
Route::get('/getReMeasuredAmendDetails/{id}', 'projectManagement@getReMeasuredAmendDetails');
Route::get('/getReMeasureSummary/{id}/{no}', 'projectManagement@getReMeasureSummary');
Route::get('/getTenderTotal/{id}', 'projectManagement@getTenderTotal');
Route::get('/getTenderQuote/{id}', 'projectManagement@getTenderQuote');
Route::get('/getAmendNo/{id}', 'projectManagement@getAmendNo');
Route::get('/chkAmend1IssueDateExists/{id}', 'projectManagement@chkAmend1IssueDateExists');
Route::get('/chkAmend2IssueDateExists/{id}', 'projectManagement@chkAmend2IssueDateExists');
Route::get('/chkAmend3IssueDateExists/{id}', 'projectManagement@chkAmend3IssueDateExists');
Route::get('/chkAmend4IssueDateExists/{id}', 'projectManagement@chkAmend4IssueDateExists');
Route::get('/getAmendIssueDate/{id}/{no}', 'projectManagement@getAmendIssueDate');
Route::get('/delKeys/{wid}/{kid}', 'projectManagement@delKeys');
Route::get('/delTerms/{wid}/{kid}', 'projectManagement@delTerms');
Route::get('/getPayments/{wid}', 'projectManagement@getPayments');
Route::get('/getEstimateTotal/{id}', 'projectManagement@getEstimateTotal');
Route::get('/getAmendSubTotals/{id}/{no}', 'projectManagement@getAmendSubTotals');
Route::get('/chkAmendPayExists/{id}/{no}', 'projectManagement@chkAmendPayExists');
Route::get('/chkAmendSchedExists/{id}/{no}', 'projectManagement@chkAmendSchedExists');
Route::get('/chkReMeasureIssueDateExists/{id}/{no}', 'projectManagement@chkReMeasureIssueDateExists');
Route::get('/getReFlag/{id}/{no}', 'projectManagement@getReFlag');
Route::get('/finishReMeasure/{id}/{no}', 'projectManagement@finishReMeasure');
Route::get('/getReItems/{id}/{no}', 'projectManagement@getReItems');
Route::get('/getRemeasureIssueDate/{id}/{no}', 'projectManagement@getRemeasureIssueDate');
Route::get('/getPrintPaySchedule/{id}/{no}', 'projectManagement@getPrintPaySchedule');
Route::get('/getAmendedLineItemsNew/{id}', 'projectManagement@getAmendedLineItemsNew');
Route::get('/getAmendLineItemsNew/{id}', 'projectManagement@getAmendedLineItemsNew');
Route::get('/getAmendedTermsNew/{id}/{no}', 'projectManagement@getAmendedTermsNew');
Route::get('/chkAmendIssueDateExists/{id}/{no}', 'projectManagement@chkAmendIssueDateExists');
Route::get('/getWorkingAmends/{id}','projectManagement@getWorkingAmends');
Route::get('/getViewWorkSchedule/{id}/{view}','projectManagement@getViewWorkSchedule');
Route::get('/finishAmendment/{wid}/{aid}','projectManagement@finishAmendment');
Route::get('/getPayAmounts/{id}','projectManagement@getPayAmounts');
Route::get('/getReTotalAmendItems/{id}/{no}','projectManagement@getReTotalAmendItems');
Route::get('/getTotalAmendedItems/{id}/{no}','projectManagement@getTotalAmendedItems');
Route::get('/getAllSubTotals/{id}','projectManagement@getAllSubTotals');
Route::get('/getAllRecievedPayments/{id}','projectManagement@getAllRecievedPayments');
Route::get('/getAllTotals/{id}','projectManagement@getAllTotals');
Route::get('/getAllPaidPayments/{id}','projectManagement@getAllPaidPayments');
Route::get('/getAllReceipts','projectManagement@getAllReceipts');
Route::get('/getAllWorkID','projectManagement@getAllWorkID');
Route::get('/getAllAssocs','projectManagement@getAllAssocs');
Route::get('/getAllCustBalances','projectManagement@getAllCustBalances');
Route::get('/getFilteredPayments/{wid}/{cid}/{tid}/{aid}/{i}/{au}/{ap}/{mf}/{af}','projectManagement@getFilteredPayments');
Route::get('/chkPaidStatus/{id}','projectManagement@chkPaidStatus');
Route::get('/getFilPayments/{Arr}','projectManagement@getFilPayments');
Route::get('/checkPaymentExists/{id}','projectManagement@checkPaymentExists');
Route::get('/getAssociateServices/{id}','projectManagement@getAssociateServices');
Route::get('/getServiceAssociates/{id}','projectManagement@getServiceAssociates');
Route::get('/getRecAmountByDate/{id}','projectManagement@getRecAmountByDate');
Route::get('/chkReasonExists/{id}','projectManagement@chkReasonExists');
Route::get('/getAmendReasons','projectManagement@getAmendReasons');
Route::get('/chkStartDateExists/{id}','projectManagement@chkStartDateExists');
Route::get('/getAllMFeeDetails','projectManagement@getAllMFeeDetails');
Route::get('/getAllPaidDetails','projectManagement@getAllPaidDetails');
Route::get('/getPayDetails/{id}','projectManagement@getPayDetails');
Route::get('/getWorkLostReason/{id}','projectManagement@getWorkLostReason');
Route::get('/getBalReceipt/{id}','projectManagement@getBalReceipt');
Route::get('/getReciptDetails/{id}','projectManagement@getReciptDetails');
Route::get('/chkMFeeExists/{id}','projectManagement@chkMFeeExists');
Route::get('/getAllReports','projectManagement@getAllReports');


//biws controller
//Route::get('/getNotifications/{id}','LoginController@getNotifications');
Route::get('/biws_generateOTP','biwsController@biws_generateOTP');
Route::get('/biws_getHash/{value}','biwsController@biws_getHash');
Route::get('/biws_getAllLeads','biwsController@biws_getAllLeads');
Route::get('/biws_getCategory','biwsController@biws_getCategory');
Route::get('/biws_AllLeadsByCust/{id}','biwsController@biws_AllLeadsByCust');
Route::get('/biws_getCustID/{name}','biwsController@biws_getCustID');
Route::get('/biws_getOneLead/{id}','biwsController@biws_getOneLead');
Route::get('/biws_chkSiteAnalysis/{id}','biwsController@biws_chkSiteAnalysis');
Route::get('/biws_AllWorks','biwsController@biws_AllWorks');
Route::get('/biws_getOneWork/{id}','biwsController@biws_getOneWork');
Route::get('/biws_getAllLineItems/{id}','biwsController@biws_getAllLineItems');
Route::get('/biws_changeStatusEst/{id}','biwsController@biws_changeStatusEst');
Route::get('/biws_getAllLabEst/{id}','biwsController@biws_getAllLabEst');
Route::get('/biws_getAllTenders/{id}','biwsController@biws_getAllTenders');
Route::get('/biws_chkKeysExists/{id}','biwsController@biws_chkKeysExists');
Route::get('/biws_getKeyDeliverables/{id}','biwsController@biws_getKeyDeliverables');
Route::get('/biws_getTerms/{id}','biwsController@biws_getTerms');
Route::get('/biws_checkTermsExists/{id}','biwsController@biws_checkTermsExists');
Route::get('/biws_chkOffTenderExists/{id}','biwsController@biws_chkOffTenderExists');
Route::get('/biws_chkOnTenderExists/{id}','biwsController@biws_chkOnTenderExists');
Route::get('/biws_getAllOfflineTenders/{id}','biwsController@biws_getAllOfflineTenders');
Route::get('/biws_getAllOfflineAssocs/{id}','biwsController@biws_getAllOfflineAssocs');
Route::get('/getAllTenderKeys/{id}','biwsController@getAllTenderKeys');
Route::get('/getAllTenderTerms/{id}','biwsController@getAllTenderTerms');
Route::get('/biws_getTenderPayTerm/{id}','biwsController@biws_getTenderPayTerm');
Route::get('/biws_getOnlineAssocs/{id}','biwsController@biws_getOnlineAssocs');
Route::get('/biws_getOnlineAssocsNew/{id}','biwsController@biws_getOnlineAssocsNew');
Route::get('/biws_getAllOnlineTenders/{id}','biwsController@biws_getAllOnlineTenders');
Route::get('/biws_getAllOnlineAssocs/{id}','biwsController@biws_getAllOnlineAssocs');
Route::get('/biws_getAllTenderList/{id}','biwsController@biws_getAllTenderList');
Route::get('/biws_chkFinishTenderExists/{id}','biwsController@biws_chkFinishTenderExists');
Route::get('/biws_AssocWorks/{id}','biwsController@biws_AssocWorks');
Route::get('/biws_getSelectedTenderAssocs/{id}','biwsController@biws_getSelectedTenderAssocs');
Route::get('/biws_getSelectedTenderItems/{id}','biwsController@biws_getSelectedTenderItems');
Route::get('/biws_chkPaymentDone/{id}','biwsController@biws_chkPaymentDone');
Route::get('/biws_getAssocTender/{aid}/{wid}','biwsController@biws_getAssocTender');
Route::get('/biws_getItemDetails/{id}','biwsController@biws_getItemDetails');
Route::get('/biws_chkWorkDaysExists/{id}','biwsController@biws_chkWorkDaysExists');
Route::get('/biws_getWorkTenderDetails/{id}','biwsController@biws_getWorkTenderDetails');
Route::get('/biws_getWorkOrderDetails/{id}','biwsController@biws_getWorkOrderDetails');
Route::get('/biws_getCustDetails/{id}','biwsController@biws_getCustDetails');
Route::get('/biws_getAssocDetails/{id}','biwsController@biws_getAssocDetails');
Route::get('/biws_getFinalTenderDetails/{id}','biwsController@biws_getFinalTenderDetails');
Route::get('/biws_getWorkSchedule/{id}','biwsController@biws_getWorkSchedule');
Route::get('/biws_getAssocID/{name}','biwsController@biws_getAssocID');
Route::get('/biws_getTenderTotal/{id}','biwsController@biws_getTenderTotal');
Route::get('/biws_chkQtyExists/{id}','biwsController@biws_chkQtyExists');
Route::get('/biws_getRejectReason','biwsController@biws_getRejectReason');
Route::get('/getTimeLineData/{id}','biwsController@getTimeLineData');
Route::get('/biws_getTenderedAssocs/{id}','biwsController@biws_getTenderedAssocs');
Route::get('/biws_getCertifyAssocList/{id}','biwsController@biws_getCertifyAssocList');
Route::get('/biws_chkRejectCount/{id}','biwsController@biws_chkRejectCount');
Route::get('/biws_AllOnlineLeadsByCust/{id}','biwsController@biws_AllOnlineLeadsByCust');
Route::get('/pdfview/{id}','biwsController@pdfview');
Route::get('/chkWOSigned/{id}','biwsController@chkWOSigned');
Route::get('/getWorkDays/{id}','biwsController@getWorkDays');
Route::get('/getItemRate/{id}','biwsController@getItemRate');
Route::get('/getStatusNames/{id}','biwsController@getStatusNames');
Route::get('/getAssocStatus/{aid}/{wid}','biwsController@getAssocStatus');
Route::get('/getUserDetails/{aid}','biwsController@getUserDetails');
Route::get('/testEmailNoti','biwsController@testEmailNoti');
Route::get('/chkContactExists/{no}','biwsController@chkContactExists');
Route::get('/chkUserExists/{no}/{email}','biwsController@chkUserExists');

Route::post('/sendMail','biwsController@sendMail');
Route::post('/biws_updateAssociate','biwsController@biws_updateAssociate');
Route::post('/biws_AssocSignUp','biwsController@biws_AssocSignUp');
Route::get('/biws_getPaySchedule/{id}','biwsController@biws_getPaySchedule');
Route::post('/biws_SignUp', 'biwsController@biws_SignUp');
Route::post('/biws_addAssociate', 'biwsController@biws_addAssociate');
Route::post('/biws_SignIn', 'biwsController@biws_SignIn');
Route::post('/biws_addLead', 'biwsController@biws_addLead');
Route::post('/biws_assocSignIn', 'biwsController@biws_assocSignIn');
Route::post('/biws_addWork', 'biwsController@biws_addWork');
Route::post('/changeCustStatus', 'biwsController@changeCustStatus');
Route::post('/biws_updateSiteAnalysisDate', 'biwsController@biws_updateSiteAnalysisDate');
Route::post('/biws_addLabLineItem', 'biwsController@biws_addLabLineItem');
Route::post('/biws_saveAssocList', 'biwsController@biws_saveAssocList');
Route::post('/biws_saveTenderKeys', 'biwsController@biws_saveTenderKeys');
Route::post('/biws_saveTerms', 'biwsController@biws_saveTerms');
Route::post('/biws_saveWorkDays', 'biwsController@biws_saveWorkDays');
Route::post('/biws_saveTenderLabDetails', 'biwsController@biws_saveTenderLabDetails');
Route::post('/biws_saveCustKeys', 'biwsController@biws_saveCustKeys');
Route::post('/biws_delInTenderKeys', 'biwsController@biws_delInTenderKeys');
Route::post('/biws_saveTenderTerms', 'biwsController@biws_saveTenderTerms');
Route::post('/biws_saveCustTerms', 'biwsController@biws_saveCustTerms');
Route::post('/biws_delInTenderTerm', 'biwsController@biws_delInTenderTerm');
Route::post('/biws_finishTender','biwsController@biws_finishTender');
Route::post('/biws_editTender','biwsController@biws_editTender');
Route::post('/biws_deleteTender','biwsController@biws_deleteTender');
Route::post('/biws_pushTenderToCust','biwsController@biws_pushTenderToCust');
Route::post('/sendLetterOfIntrest','biwsController@sendLetterOfIntrest');
Route::post('/biws_updateReqSiteVisit','biwsController@biws_updateReqSiteVisit');
Route::post('/biws_confirmAssoc','biwsController@biws_confirmAssoc');
Route::post('/biws_rejectAssoc','biwsController@biws_rejectAssoc');
Route::post('/biws_saveRate','biwsController@biws_saveRate');
Route::post('/biws_pushBackToPMA','biwsController@biws_pushBackToPMA');
Route::post('/biws_finishWO','biwsController@biws_finishWO');
Route::post('/biws_CreateToken','biwsController@biws_CreateToken');
Route::post('/biws_createTokenCust','biwsController@biws_createTokenCust');
Route::post('/biws_sendOTP','biwsController@biws_sendOTP');
Route::post('/addNewUser','biwsController@addNewUser');
Route::post('/assoc_woSigned','biwsController@assoc_woSigned');
Route::post('/cust_woSigned','biwsController@cust_woSigned');
Route::post('/saveEmailID','biwsController@saveEmailID');
Route::post('/biws_addCustomer','biwsController@biws_addCustomer');
Route::post('/biws_resetPassword','biwsController@biws_resetPassword');
Route::post('/biws_addNewEnquiry','biwsController@biws_addNewEnquiry');


//PaymentController
Route::post('/initializePayment','paymentController@initializePayment');
Route::post('/completePayment','paymentController@completePayment');


Route::get('/confirmSignature/{oid}/{pid}/{sign}','paymentController@confirmSignature');

});



